spring:
  datasource:
    url: jdbc:postgresql://192.168.9.140:5432/mariee
    username: rem
    password: qwertyuiop
  web:
    resources:
      static-locations: file:./data
  jpa:
    generate-ddl: true