spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mariee
    username: mariee
    password: qwertyuiop
  web:
    resources:
      static-locations: file:./data
  jpa:
    generate-ddl: true