spring:
  datasource:
    url: jdbc:postgresql://169.254.95.120:5432/mariee
    username: rem
    password: qwertyuiop
  web:
    resources:
      static-locations: file:./data
  jpa:
    generate-ddl: true