spring:
  datasource:
#    url: jdbc:postgresql://mariee.e3.luyouxia.net:12414/mariee
    url: jdbc:postgresql://172.16.104.254:5432/mariee
    username: rem
    password: qwertyuiop
    hikari:
      max-lifetime: 60000
  web:
    resources:
      static-locations: file:./data
  jpa:
    generate-ddl: true