spring:
  datasource:
    url: jdbc:postgresql://mariee.e3.luyouxia.net:12414/mariee
    username: rem
    password: qwertyuiop
  web:
    resources:
      static-locations: file:./data
  jpa:
    generate-ddl: true